spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/myschool
spring.datasource.username=root
spring.datasource.password=Varsh@2020

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update