spring.application.name=backend
spring.datasource.url=mysql://avnadmin:AVNS_T7VxI3cPNGfn-DUTBrq@mysql-vidyasar-harshpatle004-7a22.g.aivencloud.com:21219/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_T7VxI3cPNGfn-DUTBrq

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update